# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='server',
  syntax='proto3',
  serialized_options=b'\n\004pisaB\013ServerProtoP\001\242\002\002SP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x06server\"\x17\n\x07IsaPath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1d\n\nIsaContext\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\"\x1d\n\nIsaMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nIsaCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x19\n\x08IsaState\x12\r\n\x05state\x18\x01 \x01(\t\"\x1f\n\x0eIsaSearchWidth\x12\r\n\x05width\x18\x01 \x01(\x05\"7\n\x15IsaSearchIndexCommand\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t2\x99\x03\n\x06Server\x12;\n\x12InitialiseIsabelle\x12\x0f.server.IsaPath\x1a\x12.server.IsaMessage\"\x00\x12;\n\x0fIsabelleContext\x12\x12.server.IsaContext\x1a\x12.server.IsaMessage\"\x00\x12\x41\n\x18IsabelleWorkingDirectory\x12\x0f.server.IsaPath\x1a\x12.server.IsaMessage\"\x00\x12\x39\n\x0fIsabelleCommand\x12\x12.server.IsaCommand\x1a\x10.server.IsaState\"\x00\x12\x46\n\x16IsabelleSetSearchWidth\x12\x16.server.IsaSearchWidth\x1a\x12.server.IsaMessage\"\x00\x12O\n\x1aIsabelleSearchIndexCommand\x12\x1d.server.IsaSearchIndexCommand\x1a\x10.server.IsaState\"\x00\x42\x1a\n\x04pisaB\x0bServerProtoP\x01\xa2\x02\x02SPb\x06proto3'
)




_ISAPATH = _descriptor.Descriptor(
  name='IsaPath',
  full_name='server.IsaPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='server.IsaPath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=47,
)


_ISACONTEXT = _descriptor.Descriptor(
  name='IsaContext',
  full_name='server.IsaContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='server.IsaContext.context', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=78,
)


_ISAMESSAGE = _descriptor.Descriptor(
  name='IsaMessage',
  full_name='server.IsaMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='server.IsaMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=109,
)


_ISACOMMAND = _descriptor.Descriptor(
  name='IsaCommand',
  full_name='server.IsaCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='server.IsaCommand.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=140,
)


_ISASTATE = _descriptor.Descriptor(
  name='IsaState',
  full_name='server.IsaState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='server.IsaState.state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=167,
)


_ISASEARCHWIDTH = _descriptor.Descriptor(
  name='IsaSearchWidth',
  full_name='server.IsaSearchWidth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='server.IsaSearchWidth.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=200,
)


_ISASEARCHINDEXCOMMAND = _descriptor.Descriptor(
  name='IsaSearchIndexCommand',
  full_name='server.IsaSearchIndexCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='server.IsaSearchIndexCommand.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='server.IsaSearchIndexCommand.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=257,
)

DESCRIPTOR.message_types_by_name['IsaPath'] = _ISAPATH
DESCRIPTOR.message_types_by_name['IsaContext'] = _ISACONTEXT
DESCRIPTOR.message_types_by_name['IsaMessage'] = _ISAMESSAGE
DESCRIPTOR.message_types_by_name['IsaCommand'] = _ISACOMMAND
DESCRIPTOR.message_types_by_name['IsaState'] = _ISASTATE
DESCRIPTOR.message_types_by_name['IsaSearchWidth'] = _ISASEARCHWIDTH
DESCRIPTOR.message_types_by_name['IsaSearchIndexCommand'] = _ISASEARCHINDEXCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IsaPath = _reflection.GeneratedProtocolMessageType('IsaPath', (_message.Message,), {
  'DESCRIPTOR' : _ISAPATH,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.IsaPath)
  })
_sym_db.RegisterMessage(IsaPath)

IsaContext = _reflection.GeneratedProtocolMessageType('IsaContext', (_message.Message,), {
  'DESCRIPTOR' : _ISACONTEXT,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.IsaContext)
  })
_sym_db.RegisterMessage(IsaContext)

IsaMessage = _reflection.GeneratedProtocolMessageType('IsaMessage', (_message.Message,), {
  'DESCRIPTOR' : _ISAMESSAGE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.IsaMessage)
  })
_sym_db.RegisterMessage(IsaMessage)

IsaCommand = _reflection.GeneratedProtocolMessageType('IsaCommand', (_message.Message,), {
  'DESCRIPTOR' : _ISACOMMAND,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.IsaCommand)
  })
_sym_db.RegisterMessage(IsaCommand)

IsaState = _reflection.GeneratedProtocolMessageType('IsaState', (_message.Message,), {
  'DESCRIPTOR' : _ISASTATE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.IsaState)
  })
_sym_db.RegisterMessage(IsaState)

IsaSearchWidth = _reflection.GeneratedProtocolMessageType('IsaSearchWidth', (_message.Message,), {
  'DESCRIPTOR' : _ISASEARCHWIDTH,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.IsaSearchWidth)
  })
_sym_db.RegisterMessage(IsaSearchWidth)

IsaSearchIndexCommand = _reflection.GeneratedProtocolMessageType('IsaSearchIndexCommand', (_message.Message,), {
  'DESCRIPTOR' : _ISASEARCHINDEXCOMMAND,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.IsaSearchIndexCommand)
  })
_sym_db.RegisterMessage(IsaSearchIndexCommand)


DESCRIPTOR._options = None

_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='server.Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=260,
  serialized_end=669,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitialiseIsabelle',
    full_name='server.Server.InitialiseIsabelle',
    index=0,
    containing_service=None,
    input_type=_ISAPATH,
    output_type=_ISAMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsabelleContext',
    full_name='server.Server.IsabelleContext',
    index=1,
    containing_service=None,
    input_type=_ISACONTEXT,
    output_type=_ISAMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsabelleWorkingDirectory',
    full_name='server.Server.IsabelleWorkingDirectory',
    index=2,
    containing_service=None,
    input_type=_ISAPATH,
    output_type=_ISAMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsabelleCommand',
    full_name='server.Server.IsabelleCommand',
    index=3,
    containing_service=None,
    input_type=_ISACOMMAND,
    output_type=_ISASTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsabelleSetSearchWidth',
    full_name='server.Server.IsabelleSetSearchWidth',
    index=4,
    containing_service=None,
    input_type=_ISASEARCHWIDTH,
    output_type=_ISAMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsabelleSearchIndexCommand',
    full_name='server.Server.IsabelleSearchIndexCommand',
    index=5,
    containing_service=None,
    input_type=_ISASEARCHINDEXCOMMAND,
    output_type=_ISASTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
